name: kalman
channels:
  - defaults
dependencies:
  - ca-certificates=2021.5.25
  - certifi=2021.5.30
  - openssl=1.1.1k
  - pip=21.1.1
  - python=3.8.10
  - setuptools=52.0.0
  - sqlite=3.35.4
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wheel=0.36.2
  - wincertstore=0.2
  - pip:
    - cycler==0.10.0
    - kiwisolver==1.3.1
    - matplotlib==3.4.2
    - numpy==1.20.3
    - pillow==8.2.0
    - pyparsing==2.4.7
    - python-dateutil==2.8.1
    - pyyaml==5.4.1
    - six==1.16.0
